### ISSUE TITLE
Progress bar obscures the header

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/ubicenter.org#25]
e.g. https://ubicenter.github.io/ubicenter.org/child-allowance shows

![image](https://user-images.githubusercontent.com/6076111/106374969-cc32c900-633c-11eb-85b8-0fcaa895d563.png)

@mgilbert1

**Comment by MaxGhenis** [comment]
@mgilbert1 this is just for this one testing page right? Which we can delete since it's not the right adaptation from ipynb to md/html?

**Comment by mgilbert1** [comment]
Yeah that was just to see what it would look like, I’ll delete that once I start moving posts over

**Comment by MaxGhenis** [comment]
This was just in the weird child allowance ipynb post
