### ISSUE TITLE
Show logo in upper left when scrolling down in post page

### ISSUE THREAD

**Issue by MaxGhenis** [UBICenter/ubicenter.org#99]
I think we're missing a logo file somewhere. Scrolling down in [this sample jasper2 page](https://jekyller.github.io/jasper2/welcome) shows the logo next to the site name in the upper left:
![image](https://user-images.githubusercontent.com/6076111/113487830-25b79100-946f-11eb-9682-302f57fa494a.png)

That doesn't show up on our pages, e.g. https://ubicenter.github.io/ubicenter.org/womens-day-2021:

![image](https://user-images.githubusercontent.com/6076111/113487839-3cf67e80-946f-11eb-8130-da4140f6b29f.png)

@yuchida522 could you take a look?

**Comment by yuchida522** [comment]
It looks like it's there but the color needs to be darker, so I will fix that!
